apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1729603589114
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: acrworkflow1729603589114.azurecr.io/blazorisland
          resources:
            limits:
              cpu: "200m"
              memory: "250Mi"
            requests:
              cpu: "100m"
              memory: "20Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: namespace-workflow-1729603589114
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  namespace: namespace-workflow-1729603589114
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: cloudflare-letsencrypt
    kubernetes.io/tls-acme: "true"
    external-dns.alpha.kubernetes.io/hostname: "blazorisland.core-connect.io"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
    - hosts:
        - blazorisland.core-connect.io
      secretName: blazorisland-letsencrypt
  rules:
    - host: blazorisland.core-connect.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 8080
